In [1]:
import inputs.vents as v
import inputs.polaires as p

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = "data/grib_vent/20260422_070337_GFS_P25_00.grb2"
df = v.table(path)
df

,latitude,longitude,valid_time,force,direction,temps,x_data,y_data
0,31.5,0.25,2026-04-22,5.123264,297.945862,0.0,10.5,1890.0
1,31.5,341.25,2026-04-22,4.968140,306.357574,0.0,14332.5,1890.0
2,31.5,341.50,2026-04-22,5.271007,313.458771,0.0,14343.0,1890.0
3,31.5,341.75,2026-04-22,5.255155,322.164795,0.0,14353.5,1890.0
4,31.5,342.00,2026-04-22,4.729717,325.496246,0.0,14364.0,1890.0
...,...,...,...,...,...,...,...,...
405400,47.5,359.00,2026-05-02,6.923615,6.430145,240.0,15078.0,2850.0
405401,47.5,359.25,2026-05-02,6.851637,5.354004,240.0,15088.5,2850.0
405402,47.5,359.50,2026-05-02,7.580052,14.842224,240.0,15099.0,2850.0
405403,47.5,359.75,2026-05-02,8.119076,17.685638,240.0,15109.5,2850.0
405404,47.5,360.00,2026-05-02,7.749620,13.325729,240.0,15120.0,2850.0

In [3]:
VENT_NM = v.vent_grib_nm(path)
VENT_DEG = v.vent_grib_deg(path)

In [4]:
path = "data/polaires/vector.csv"
POLAIRE = p.polaire(path)

In [5]:
%matplotlib qt

In [6]:
import cProfile
import core.isochrone as iso

In [10]:
# # p_dep = [46, 2]
# # p_arr = [44, 9]
# # p_dep = [44.53, 360-6.06, 0, 0]
# # p_arr = [48.2, 360-5.6]
p_dep = [44, 360-16]
p_arr = [40, 360-16]
p_dep = [p_dep[1] * 60 * 0.7, p_dep[0] * 60, 0, 0]
p_arr = [p_arr[1] * 60 * 0.7, p_arr[0] * 60]
t = 0

# def VENT_NM(p, t):
#     return VENT(p, t, 'nm')

L = iso.n_iso(N = 80, p_dep = p_dep, p_arr = p_arr, t = t, dt = 0.5, n = 100, V = VENT_NM, P = POLAIRE, k_voisins = 100, ang = np.pi/2, dang = np.radians(0.1), delta = 1)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 0.50 heures, nombre de points : 100
nombre isochrones : 2, temps écoulé : 1.00 heures, nombre de points : 62
nombre isochrones : 3, temps écoulé : 1.50 heures, nombre de points : 90
nombre isochrones : 4, temps écoulé : 2.00 heures, nombre de points : 122
nombre isochrones : 5, temps écoulé : 2.50 heures, nombre de points : 145
nombre isochrones : 6, temps écoulé : 3.00 heures, nombre de points : 167
nombre isochrones : 7, temps écoulé : 3.50 heures, nombre de points : 190
nombre isochrones : 8, temps écoulé : 4.00 heures, nombre de points : 222
nombre isochrones : 9, temps écoulé : 4.50 heures, nombre de points : 238
nombre isochrones : 10, temps écoulé : 5.00 heures, nombre de points : 260
nombre isochrones : 11, temps écoulé : 5.50 heures, nombre de points : 278
nombre isochrones : 12, temps écoulé : 6.00 heures, nombre de points : 302
nombre isochrones : 13, temps écoulé : 6.50 heures, nombre de points : 323
nombre isochrones : 14, temps écoulé : 7.00 heures, nombre de points : 339
nombre isochrones : 15, temps écoulé : 7.50 heures, nombre de points : 357
nombre isochrones : 16, temps écoulé : 8.00 heures, nombre de points : 370
nombre isochrones : 17, temps écoulé : 8.50 heures, nombre de points : 406
nombre isochrones : 18, temps écoulé : 9.00 heures, nombre de points : 438
nombre isochrones : 19, temps écoulé : 9.50 heures, nombre de points : 457
nombre isochrones : 20, temps écoulé : 10.00 heures, nombre de points : 462
nombre isochrones : 21, temps écoulé : 10.50 heures, nombre de points : 463
nombre isochrones : 22, temps écoulé : 11.00 heures, nombre de points : 466
nombre isochrones : 23, temps écoulé : 11.50 heures, nombre de points : 475
nombre isochrones : 24, temps écoulé : 12.00 heures, nombre de points : 487
nombre isochrones : 25, temps écoulé : 12.50 heures, nombre de points : 499
nombre isochrones : 26, temps écoulé : 13.00 heures, nombre de points : 516
nombre isochrones : 27, temps écoulé : 13.50 heures, nombre de points : 530
nombre isochrones : 28, temps écoulé : 14.00 heures, nombre de points : 532
nombre isochrones : 29, temps écoulé : 14.50 heures, nombre de points : 536
nombre isochrones : 30, temps écoulé : 15.00 heures, nombre de points : 559
nombre isochrones : 31, temps écoulé : 15.50 heures, nombre de points : 582
nombre isochrones : 32, temps écoulé : 16.00 heures, nombre de points : 623
nombre isochrones : 33, temps écoulé : 16.50 heures, nombre de points : 657
nombre isochrones : 34, temps écoulé : 17.00 heures, nombre de points : 691
nombre isochrones : 35, temps écoulé : 17.50 heures, nombre de points : 742
nombre isochrones : 36, temps écoulé : 18.00 heures, nombre de points : 777
nombre isochrones : 37, temps écoulé : 18.50 heures, nombre de points : 800
nombre isochrones : 38, temps écoulé : 19.00 heures, nombre de points : 817
nombre isochrones : 39, temps écoulé : 19.50 heures, nombre de points : 837
nombre isochrones : 40, temps écoulé : 20.00 heures, nombre de points : 882
nombre isochrones : 41, temps écoulé : 20.50 heures, nombre de points : 863
nombre isochrones : 42, temps écoulé : 21.00 heures, nombre de points : 879
nombre isochrones : 43, temps écoulé : 21.50 heures, nombre de points : 884
nombre isochrones : 44, temps écoulé : 22.00 heures, nombre de points : 903
nombre isochrones : 45, temps écoulé : 22.50 heures, nombre de points : 910
nombre isochrones : 46, temps écoulé : 23.00 heures, nombre de points : 944
nombre isochrones : 47, temps écoulé : 23.50 heures, nombre de points : 993
nombre isochrones : 48, temps écoulé : 24.00 heures, nombre de points : 1023
nombre isochrones : 49, temps écoulé : 24.50 heures, nombre de points : 1042
nombre isochrones : 50, temps écoulé : 25.00 heures, nombre de points : 1083
nombre isochrones : 51, temps écoulé : 25.50 heures, nombre de points : 1129
nombre isochrones : 52, temps écoulé : 26.00 heures, nombre de points : 1179
nombre isochrones : 53, temps écoulé : 26.50 heures, nombre de points : 1228
nombre isochrones : 54, temps écoulé : 27.00 heures, nombre de points : 1278
nombre isochrones : 55, temps écoulé : 27.50 heures, nombre de points : 1310
nombre isochrones : 56, temps écoulé : 28.00 heures, nombre de points : 1349
nombre isochrones : 57, temps écoulé : 28.50 heures, nombre de points : 1373
nombre isochrones : 58, temps écoulé : 29.00 heures, nombre de points : 1397
nombre isochrones : 59, temps écoulé : 29.50 heures, nombre de points : 1367
nombre isochrones : 60, temps écoulé : 30.00 heures, nombre de points : 1371
nombre isochrones : 61, temps écoulé : 30.50 heures, nombre de points : 1399
nombre isochrones : 62, temps écoulé : 31.00 heures, nombre de points : 1420
nombre isochrones : 63, temps écoulé : 31.50 heures, nombre de points : 1423
nombre isochrones : 64, temps écoulé : 32.00 heures, nombre de points : 1414
nombre isochrones : 65, temps écoulé : 32.50 heures, nombre de points : 1486
nombre isochrones : 66, temps écoulé : 33.00 heures, nombre de points : 1536
nombre isochrones : 67, temps écoulé : 33.50 heures, nombre de points : 1606
nombre isochrones : 68, temps écoulé : 34.00 heures, nombre de points : 1668
nombre isochrones : 69, temps écoulé : 34.50 heures, nombre de points : 1708
nombre isochrones : 70, temps écoulé : 35.00 heures, nombre de points : 1780
nombre isochrones : 71, temps écoulé : 35.50 heures, nombre de points : 1942
nombre isochrones : 72, temps écoulé : 36.00 heures, nombre de points : 2054
nombre isochrones : 73, temps écoulé : 36.50 heures, nombre de points : 2191
nombre isochrones : 74, temps écoulé : 37.00 heures, nombre de points : 2217
nombre isochrones : 75, temps écoulé : 37.50 heures, nombre de points : 2264
nombre isochrones : 76, temps écoulé : 38.00 heures, nombre de points : 2207
nombre isochrones : 77, temps écoulé : 38.50 heures, nombre de points : 2230
nombre isochrones : 78, temps écoulé : 39.00 heures, nombre de points : 2283
nombre isochrones : 79, temps écoulé : 39.50 heures, nombre de points : 2306
nombre isochrones : 80, temps écoulé : 40.00 heures, nombre de points : 2334

In [11]:
plt.scatter(L[:, 0], L[:, 1], c = 'blue')
plt.axis('equal')

(np.float64(14031.502713920843),
 np.float64(14791.497541846427),
 np.float64(2415.470988997546),
 np.float64(2657.6986886504264))

In [13]:
I = L[L[:, 2] == 80]

In [14]:
N = iso.nuage_iso(I, t = 40, dt = 0.5, n = 100, V = VENT_NM, P = POLAIRE)

In [15]:
import core.enveloppe as e
E = e.enveloppe(N, k_voisins = 100, p_dep = p_dep, p_arr = p_arr, ang = np.pi/2 - 80 * np.radians(0.1), delta = 1)

ValueError: Aucun voisin trouvé parmi les 100 plus proches voisins.

In [19]:
from scipy.spatial import cKDTree
import core.utils as f

ang = np.pi/2 - 80 * np.radians(0.1)
delta = 1
k_voisins = 100


p_dep = np.array(p_dep, dtype=float)
p_arr = np.array(p_arr, dtype=float)
dir = f.angle_direction(p_dep, p_arr)
p1, p = e.points_les_plus_a(N, dir + ang, p_dep, delta)

tree = cKDTree(N[:, :2])
kv = min(k_voisins, len(N))
voisins1 = N[np.atleast_1d(tree.query(p1[:2], k=kv)[1])]

angles1 = f.angle_oriente_positif(p, p1, voisins1)

# gestion cas 2 angles égaux
max_angle = np.max(angles1)
eps = 1e-12
candidats = np.where(np.abs(angles1 - max_angle) < eps)[0]
if len(candidats) == 1:
    idx = candidats[0]
else:
    dists = np.linalg.norm(voisins1[candidats, :2] - p1[:2], axis=1)
    idx = candidats[np.argmin(dists)]

p2 = voisins1[idx]

max_points = 10000   # borne large mais sûre
l = np.empty((max_points, N.shape[1]))
l[0] = p
l[1] = p1
l[2] = p2
k = 3

angle_g = f.angle_oriente_negatif(l[1], p_dep, p_arr)
angle_oriente = f.angle_oriente_negatif(l[1], p_dep, l[k-1])

In [23]:
for _ in range(100): 
    voisins = N[np.atleast_1d(tree.query(p2[:2], k=kv)[1])]
    angles = f.angle_oriente_positif(p1, p2, voisins)

    # gestion cas 2 angles égaux
    max_angle = np.max(angles)
    candidats = np.where(np.abs(angles - max_angle) < eps)[0]
    if len(candidats) == 1:
        idx = candidats[0]
    else:
        dists = np.linalg.norm(voisins[candidats, :2] - p2[:2], axis=1)
        idx = candidats[np.argmin(dists)]

    p3 = voisins[idx]

    if max_angle > np.pi:

        while e.bouclage(l[:k], p3):
            mask = np.ones(len(voisins), dtype=bool)
            mask[idx] = False
            voisins = voisins[mask]
            angles = angles[mask]
            if voisins.size == 0:
                raise ValueError(f"Aucun voisin trouvé parmi les {k_voisins} plus proches voisins.")

            # gestion cas 2 angles égaux
            max_angle = np.max(angles)
            candidats = np.where(np.abs(angles - max_angle) < eps)[0]
            if len(candidats) == 1:
                idx = candidats[0]
            else:
                dists = np.linalg.norm(voisins[candidats, :2] - p2[:2], axis=1)
                idx = candidats[np.argmin(dists)]

            p3 = voisins[idx]

    l[k] = p3
    k += 1
    p1, p2 = p2, p3
    angle_oriente = f.angle_oriente_negatif(l[1], p_dep, l[k-1])

ValueError: Aucun voisin trouvé parmi les 100 plus proches voisins.

In [24]:
plt.scatter(N[:, 0], N[:, 1], c = 'grey')
plt.scatter(I[:, 0], I[:, 1], c = 'blue')
# plt.scatter(E[:, 0], E[:, 1], c = 'red')
plt.scatter(l[:k][:, 0], l[:k][:, 1], c = 'red')
plt.axis('equal')

(np.float64(14024.805603748246),
 np.float64(14792.830092196495),
 np.float64(2415.1645836732555),
 np.float64(2610.470541323733))

In [9]:
p_dep = [44, 360-16]
p_arr = [40, 360-16]
t = 0

routage = iso.routage(p_dep, p_arr, t, dt = 0.5, n = 100, V = VENT_NM, P = POLAIRE, e_arr = 5, k_voisins = 100, ang = np.pi/2, dang = np.radians(0.1), delta = 1)

# cProfile.run("routage = iso.routage(p_dep, p_arr, t, dt = 0.25, n = 100, V = VENT, P = POLAIRE, e_arr = 5, r = 0.5, ang = np.pi/2, dang = np.radians(0.4), delta = 0.1)",
#             sort="tottime")

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 0.50 heures, nombre de points : 100
nombre isochrones : 2, temps : 1.00 heures, nombre de points : 62
nombre isochrones : 3, temps : 1.50 heures, nombre de points : 90
nombre isochrones : 4, temps : 2.00 heures, nombre de points : 122
nombre isochrones : 5, temps : 2.50 heures, nombre de points : 145
nombre isochrones : 6, temps : 3.00 heures, nombre de points : 167
nombre isochrones : 7, temps : 3.50 heures, nombre de points : 190
nombre isochrones : 8, temps : 4.00 heures, nombre de points : 222
nombre isochrones : 9, temps : 4.50 heures, nombre de points : 238
nombre isochrones : 10, temps : 5.00 heures, nombre de points : 260
nombre isochrones : 11, temps : 5.50 heures, nombre de points : 278
nombre isochrones : 12, temps : 6.00 heures, nombre de points : 302
nombre isochrones : 13, temps : 6.50 heures, nombre de points : 323
nombre isochrones : 14, temps : 7.00 heures, nombre de points : 339
nombre isochrones : 15, temps : 7.50 heures, nombre de points : 357
nombre isochrones : 16, temps : 8.00 heures, nombre de points : 370
nombre isochrones : 17, temps : 8.50 heures, nombre de points : 406
nombre isochrones : 18, temps : 9.00 heures, nombre de points : 438
nombre isochrones : 19, temps : 9.50 heures, nombre de points : 457
nombre isochrones : 20, temps : 10.00 heures, nombre de points : 462
nombre isochrones : 21, temps : 10.50 heures, nombre de points : 463
nombre isochrones : 22, temps : 11.00 heures, nombre de points : 466
nombre isochrones : 23, temps : 11.50 heures, nombre de points : 475
nombre isochrones : 24, temps : 12.00 heures, nombre de points : 487
nombre isochrones : 25, temps : 12.50 heures, nombre de points : 499
nombre isochrones : 26, temps : 13.00 heures, nombre de points : 516
nombre isochrones : 27, temps : 13.50 heures, nombre de points : 530
nombre isochrones : 28, temps : 14.00 heures, nombre de points : 532
nombre isochrones : 29, temps : 14.50 heures, nombre de points : 536
nombre isochrones : 30, temps : 15.00 heures, nombre de points : 559
nombre isochrones : 31, temps : 15.50 heures, nombre de points : 582
nombre isochrones : 32, temps : 16.00 heures, nombre de points : 623
nombre isochrones : 33, temps : 16.50 heures, nombre de points : 657
nombre isochrones : 34, temps : 17.00 heures, nombre de points : 691
nombre isochrones : 35, temps : 17.50 heures, nombre de points : 742
nombre isochrones : 36, temps : 18.00 heures, nombre de points : 777
nombre isochrones : 37, temps : 18.50 heures, nombre de points : 800
nombre isochrones : 38, temps : 19.00 heures, nombre de points : 817
nombre isochrones : 39, temps : 19.50 heures, nombre de points : 837
nombre isochrones : 40, temps : 20.00 heures, nombre de points : 882
nombre isochrones : 41, temps : 20.50 heures, nombre de points : 863
nombre isochrones : 42, temps : 21.00 heures, nombre de points : 879
nombre isochrones : 43, temps : 21.50 heures, nombre de points : 884
nombre isochrones : 44, temps : 22.00 heures, nombre de points : 903
nombre isochrones : 45, temps : 22.50 heures, nombre de points : 910
nombre isochrones : 46, temps : 23.00 heures, nombre de points : 944
nombre isochrones : 47, temps : 23.50 heures, nombre de points : 993
nombre isochrones : 48, temps : 24.00 heures, nombre de points : 1023
nombre isochrones : 49, temps : 24.50 heures, nombre de points : 1042
nombre isochrones : 50, temps : 25.00 heures, nombre de points : 1083
nombre isochrones : 51, temps : 25.50 heures, nombre de points : 1129
nombre isochrones : 52, temps : 26.00 heures, nombre de points : 1179
nombre isochrones : 53, temps : 26.50 heures, nombre de points : 1228
nombre isochrones : 54, temps : 27.00 heures, nombre de points : 1278
nombre isochrones : 55, temps : 27.50 heures, nombre de points : 1310
nombre isochrones : 56, temps : 28.00 heures, nombre de points : 1349
nombre isochrones : 57, temps : 28.50 heures, nombre de points : 1373
nombre isochrones : 58, temps : 29.00 heures, nombre de points : 1397
nombre isochrones : 59, temps : 29.50 heures, nombre de points : 1367
nombre isochrones : 60, temps : 30.00 heures, nombre de points : 1371
nombre isochrones : 61, temps : 30.50 heures, nombre de points : 1399
nombre isochrones : 62, temps : 31.00 heures, nombre de points : 1420
nombre isochrones : 63, temps : 31.50 heures, nombre de points : 1423
nombre isochrones : 64, temps : 32.00 heures, nombre de points : 1414
nombre isochrones : 65, temps : 32.50 heures, nombre de points : 1486
nombre isochrones : 66, temps : 33.00 heures, nombre de points : 1536
nombre isochrones : 67, temps : 33.50 heures, nombre de points : 1606
nombre isochrones : 68, temps : 34.00 heures, nombre de points : 1668
nombre isochrones : 69, temps : 34.50 heures, nombre de points : 1708
nombre isochrones : 70, temps : 35.00 heures, nombre de points : 1780
nombre isochrones : 71, temps : 35.50 heures, nombre de points : 1942
nombre isochrones : 72, temps : 36.00 heures, nombre de points : 2054
nombre isochrones : 73, temps : 36.50 heures, nombre de points : 2191
nombre isochrones : 74, temps : 37.00 heures, nombre de points : 2217
nombre isochrones : 75, temps : 37.50 heures, nombre de points : 2264
nombre isochrones : 76, temps : 38.00 heures, nombre de points : 2207
nombre isochrones : 77, temps : 38.50 heures, nombre de points : 2230
nombre isochrones : 78, temps : 39.00 heures, nombre de points : 2283
nombre isochrones : 79, temps : 39.50 heures, nombre de points : 2306
nombre isochrones : 80, temps : 40.00 heures, nombre de points : 2334

ValueError: Aucun voisin trouvé parmi les 100 plus proches voisins.

In [24]:
latitude, longitude, time_list, L = routage

t_arr = time_list[-1]
print((t_arr - t) // 24, "jours", (t_arr - t) % 24, "heures")

0.0 jours 20.0 heures

In [118]:
v.aff_vent_static(VENT_NM, 0, [14000, 15000], [2200, 2800], 50)

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())

ax.add_feature(cfeature.BORDERS, linewidth=1)
ax.add_feature(cfeature.COASTLINE, linewidth=1)

gl = ax.gridlines(draw_labels=True,
                  crs=ccrs.PlateCarree(),
                  linestyle='--',
                  alpha=0.6)

gl.top_labels = False
gl.right_labels = False

# -------------------------
# GRILLE
# -------------------------
V = VENT_DEG
t = 6

intx = [350, 360]
inty = [42, 49]
n = 60

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)

X, Y = np.meshgrid(lon, lat)

# -------------------------
# CALCUL DU VENT
# -------------------------
U = np.zeros_like(X)
Vv = np.zeros_like(Y)
C = np.zeros_like(X)

for i in range(n+1):
    for j in range(n+1):
        direction, speed = V([X[i,j], Y[i,j]], t)
        
        U[i,j] = - speed * np.sin(np.radians(direction))
        Vv[i,j] = - speed * np.cos(np.radians(direction))
        C[i,j] = speed

# -------------------------
# QUIVER
# -------------------------
q = ax.quiver(X, Y, U, Vv, C,
              transform=ccrs.PlateCarree(),
              cmap='Greys')

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# route 
# ax.plot(longitude, latitude, transform=ccrs.PlateCarree(), c = 'red')
# ax.scatter(longitude, latitude, transform=ccrs.PlateCarree(), c = 'red')

plt.show()

In [25]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from datetime import datetime, timedelta

# -------------------------
# Paramètres de la grille
# -------------------------
V = VENT_DEG  # votre fonction de vent

# intx = [min(pd.unique(df['longitude'])), max(pd.unique(df['longitude']))]
inty = [min(pd.unique(df['latitude'])), max(pd.unique(df['latitude']))]
intx = [341.25, max(pd.unique(df['longitude']))]
intt = [0, max(pd.unique(df['temps']))]
n = 100

start_date = df['valid_time'][0]

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)
X, Y = np.meshgrid(lon, lat)

# -------------------------
# Initialisation figure
# -------------------------
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
# ax.add_feature(cfeature.BORDERS, linewidth=1)
ax.add_feature(cfeature.COASTLINE, linewidth=1)
# ax.add_feature(cfeature.NaturalEarthFeature('physical', 'land', '10m'), linewidth=1)

gl = ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                  linestyle='--', alpha=0.6)
gl.top_labels = False
gl.right_labels = False

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# -------------------------
# Fonction pour calculer vent
# -------------------------
def compute_wind(t):
    U = np.zeros_like(X)
    Vv = np.zeros_like(Y)
    C = np.zeros_like(X)
    for i in range(n+1):
        for j in range(n+1):
            direction, speed = VENT_DEG([X[i,j], Y[i,j]], t)
            U[i,j] = - speed * np.sin(np.radians(direction))
            Vv[i,j] = - speed * np.cos(np.radians(direction))
            if speed > 20:
                C[i,j] = 20
            else:
                C[i,j] = speed
    return U, Vv, C

# -------------------------
# Vent initial t=0
# -------------------------
initial_time = intt[0]
U, Vv, C = compute_wind(initial_time)
q = ax.quiver(X, Y, U, Vv, C, transform=ccrs.PlateCarree(), cmap='Greys')


# -------------------------
# Route
# -------------------------
for i in range(len(latitude)):
    l = L[L[:, 2] == i]
    ax.plot(l[:, 1], l[:, 0], transform=ccrs.PlateCarree(), c = 'lightcoral')
    
route_line, = ax.plot(longitude, latitude, transform=ccrs.PlateCarree(), c='red')
boat_scatter = ax.scatter(latitude[0], longitude[0], c='red', transform=ccrs.PlateCarree())

# -------------------------
# Slider
# -------------------------
ax_slider = plt.axes([0.2, 0.02, 0.6, 0.03])
slider = Slider(ax_slider, 'Temps', valmin=intt[0], valmax=intt[1], valinit=intt[0], valstep=1, facecolor='grey')
slider.vline.set_visible(False)

initial_date = start_date + timedelta(hours=initial_time)
slider.valtext.set_text(initial_date.strftime("%d/%m %H:%M"))


def update(val):
    t = slider.val
    U, Vv, C = compute_wind(t)
    q.set_UVC(U, Vv, C)

    # date
    current_date = start_date + timedelta(hours=t)
    slider.valtext.set_text(current_date.strftime("%d/%m %H:%M"))

    # Route
    idx = np.argmin(np.abs(time_list - t))
    boat_scatter.set_offsets([[longitude[idx], latitude[idx]]])

    fig.canvas.draw_idle()

slider.on_changed(update)

plt.show()

In [27]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from datetime import datetime, timedelta

# -------------------------
# Paramètres de la grille
# -------------------------
V = VENT_DEG  # votre fonction de vent

inty = [min(pd.unique(df['latitude'])), max(pd.unique(df['latitude']))]
intx = [341.25, max(pd.unique(df['longitude']))]
intt = [0, max(pd.unique(df['temps']))]
n = 100

start_date = df['valid_time'][0]

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)
X, Y = np.meshgrid(lon, lat)

# -------------------------
# Initialisation figure
# -------------------------
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)

gl = ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                  linestyle='--', alpha=0.6)
gl.top_labels = False
gl.right_labels = False

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# -------------------------
# Fonction pour calculer vent
# -------------------------
def compute_wind(t):
    U = np.zeros_like(X)
    Vv = np.zeros_like(Y)
    C = np.zeros_like(X)
    for i in range(n+1):
        for j in range(n+1):
            direction, speed = VENT_DEG([X[i,j], Y[i,j]], t)
            U[i,j] = - speed * np.sin(np.radians(direction))
            Vv[i,j] = - speed * np.cos(np.radians(direction))
            if speed > 15:
                C[i,j] = 15
            else:
                C[i,j] = speed
    return U, Vv, C

# -------------------------
# Fonction pour calculer le titre
# -------------------------
def compute_title(idx, t):
    pos = [longitude[idx], latitude[idx]]

    wind_dir, wind_speed = VENT_DEG(pos, t)
    wind_dir   = float(wind_dir)
    wind_speed = float(wind_speed)

    if idx < len(longitude) - 1:
        next_pos = [longitude[idx + 1], latitude[idx + 1]]
        dlat = float(next_pos[1] - pos[1])
        dlon = float(next_pos[0] - pos[0])
    else:
        prev_pos = [longitude[idx - 1], latitude[idx - 1]]
        dlat = float(pos[1] - prev_pos[1])
        dlon = float(pos[0] - prev_pos[0])

    boat_heading = np.degrees(np.arctan2(dlon, dlat)) % 360

    twa = (boat_heading - wind_dir + 180) % 360 - 180

    boat_speed = float(POLAIRE(abs(twa), wind_speed))

    return wind_speed, twa, boat_speed

# -------------------------
# Vent initial t=0
# -------------------------
initial_time = intt[0]
U, Vv, C = compute_wind(initial_time)
q = ax.quiver(X, Y, U, Vv, C, transform=ccrs.PlateCarree(), cmap='Greys')

# Titre initial
idx0 = np.argmin(np.abs(time_list - initial_time))
ws0, twa0, bs0 = compute_title(idx0, initial_time)
title = ax.set_title(
    f"Vent : {ws0:.1f} kts  |  TWA : {twa0:.1f}°  |  Vitesse : {bs0:.1f} kts",
    fontsize=10, pad=10
)

# -------------------------
# Route
# -------------------------
for i in range(len(latitude)):
    l = L[L[:, 2] == i]
    ax.plot(l[:, 1], l[:, 0], transform=ccrs.PlateCarree(), c='lightcoral')

route_line, = ax.plot(longitude, latitude, transform=ccrs.PlateCarree(), c='red')
boat_scatter = ax.scatter(longitude[0], latitude[0], c='red', transform=ccrs.PlateCarree())

# -------------------------
# Slider
# -------------------------
ax_slider = plt.axes([0.2, 0.02, 0.6, 0.03])
slider = Slider(ax_slider, 'Temps', valmin=intt[0], valmax=intt[1],
                valinit=intt[0], valstep=1, facecolor='grey')
slider.vline.set_visible(False)

initial_date = start_date + timedelta(hours=initial_time)
slider.valtext.set_text(initial_date.strftime("%d/%m %H:%M"))

def update(val):
    t = slider.val
    U, Vv, C = compute_wind(t)
    q.set_UVC(U, Vv, C)

    # Date slider
    current_date = start_date + timedelta(hours=t)
    slider.valtext.set_text(current_date.strftime("%d/%m %H:%M"))

    # Position bateau
    idx = np.argmin(np.abs(time_list - t))
    boat_scatter.set_offsets([[longitude[idx], latitude[idx]]])

    # Mise à jour du titre
    wind_speed, twa, boat_speed = compute_title(idx, t)
    title.set_text(
        f"Vent : {wind_speed:.1f} kts  |  TWA : {twa:.1f}°  |  Vitesse : {boat_speed:.1f} kts"
    )

    fig.canvas.draw_idle()

slider.on_changed(update)

plt.show()

/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))

/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))
/var/folders/8l/778p2v1d5019h4kmk2r9svjh0000gn/T/ipykernel_10796/2541969327.py:80: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  boat_speed = float(POLAIRE(abs(twa), wind_speed))

In [ ]:
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)
# ax.add_feature(cfeature.NaturalEarthFeature('physical', 'land', '10m'), linewidth=1

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely import contains_xy
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def points_sur_terre_ou_mer(coords):
    coords[:, 0], coords[:, 1] = coords[:, 1] / 60, coords[:, 0] / (60 * 0.7)
    lat = coords[:, 0]
    lon = coords[:, 1]

    # Test vectorisé
    return ~contains_xy(land_geom, lon, lat)

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely.geometry import Point
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def valide_nm(x, y):
    lat, lon = y / 60, x / (60 * 0.7)
    p = Point(lon, lat)
    return not land_geom.contains(p)

def valide_deg(lat, lon):
    lon = lon - 360
    p = Point(lon, lat)
    return not land_geom.contains(p)

In [ ]:
valide_deg(46, 358)

In [ ]:
valide_nm(0 * 60 * 0.7, 46 * 60)

In [ ]:
VENT([46, 358], 6, 'deg')

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely.geometry import Point
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def point_sur_terre_ou_mer(lat, lon):
    p = Point(lon, lat)   # attention : Point(x, y) = Point(lon, lat)
    return not land_geom.contains(p)

In [ ]:
point_sur_terre_ou_mer(46, 359)

In [ ]:
import pandas as pd
import numpy as np

def table_terre_mer(lat_start, lat_end, lon_start, lon_end, lat_step, lon_step):
    lats = np.arange(lat_start, lat_end + lat_step, lat_step)
    lons = np.arange(lon_start, lon_end + lon_step, lon_step)
    lat_grid, lon_grid = np.meshgrid(lats, lons, indexing='ij')
    flat_lats = lat_grid.ravel()
    flat_lons = lon_grid.ravel()
    # Utilise numpy pour la grille, mais reste une boucle sur le point_sur_terre_ou_mer
    values = np.array([point_sur_terre_ou_mer(lat, lon) for lat, lon in zip(flat_lats, flat_lons)])
    df = pd.DataFrame({
        "latitude": flat_lats,
        "longitude": flat_lons,
        "terre_mer": values
    })
    return df

# Exemple d'utilisation :
df = table_terre_mer(43.0, 50.0, -8.0, 0.0, 0.05, 0.05)
print(df)

In [ ]:
fig = plt.figure(figsize=(8, 6))
ax = plt.axes(projection=ccrs.PlateCarree())
scatter = ax.scatter(df["longitude"], df["latitude"], c=df["terre_mer"], cmap="bwr", marker="o", s=10, transform=ccrs.PlateCarree())
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
ax.set_title("Points Terre/Mer (0 = Terre, 1 = Mer)")
plt.colorbar(scatter, ticks=[0, 1], label="Terre (0) / Mer (1)")
ax.add_feature(cfeature.COASTLINE, linewidth=1)
plt.show()

In [ ]:
import pandas as pd

# On ouvre le fichier CSV data/polaires/vector.csv et on l'affiche
df = pd.read_csv("data/polaires/vector.csv")
df

    TWA/TWS  0    6    8   12    16    20    25    30    40
0         0  0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
1        10  0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
2        20  0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
3        30  0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
4        40  0  2.7  3.5  4.0   5.0   5.2   2.7   2.3   2.3
5        50  0  3.9  4.6  5.5   6.2   6.6   5.0   3.8   3.8
6        60  0  4.7  5.7  6.5   7.2   7.4   7.0   6.2   6.2
7        70  0  5.0  6.1  7.1   7.9   8.1   8.4   8.0   8.0
8        80  0  5.2  6.3  7.8   9.0   9.7  10.1   9.6   9.6
9        90  0  5.2  6.4  8.3   9.9  11.2  11.6  10.6  10.6
10      100  0  5.2  6.6  8.3  10.5  12.8  13.1  11.6  11.6
11      110  0  4.9  6.5  8.4  10.7  13.0  13.4  12.4  12.4
12      120  0  4.5  6.2  8.4  10.8  13.1  13.6  13.0  13.0
13      130  0  3.9  5.7  8.4  10.5  13.3  14.3  13.2  13.2
14      140  0  3.3  4.8  7.4   9.5  13.4  14.8  13.1  13.1
15      150  0  2.6  3.7  6.0   7.9  11.4  13.8  12.1  12.1
16      160  0  2.2  3.1  5.0   6.5   8.6  10.8  10.6  10.6
17      170  0  2.0  3.0  4.5   6.0   8.0   9.0  10.0  10.0
18      180  0  2.0  3.0  4.5   6.0   8.0   9.0  10.0  10.0

In [ ]:
df.iloc[:, 0]

0       0
1      10
2      20
3      30
4      40
5      50
6      60
7      70
8      80
9      90
10    100
11    110
12    120
13    130
14    140
15    150
16    160
17    170
18    180
Name: TWA/TWS, dtype: int64

In [ ]:
df.iloc[0, 1:]

0     0.0
6     0.0
8     0.0
12    0.0
16    0.0
20    0.0
25    0.0
30    0.0
40    0.0
Name: 0, dtype: float64

In [ ]:
df.iloc[:, 1:]

    0    6    8   12    16    20    25    30    40
0   0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
1   0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
2   0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
3   0  0.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0
4   0  2.7  3.5  4.0   5.0   5.2   2.7   2.3   2.3
5   0  3.9  4.6  5.5   6.2   6.6   5.0   3.8   3.8
6   0  4.7  5.7  6.5   7.2   7.4   7.0   6.2   6.2
7   0  5.0  6.1  7.1   7.9   8.1   8.4   8.0   8.0
8   0  5.2  6.3  7.8   9.0   9.7  10.1   9.6   9.6
9   0  5.2  6.4  8.3   9.9  11.2  11.6  10.6  10.6
10  0  5.2  6.6  8.3  10.5  12.8  13.1  11.6  11.6
11  0  4.9  6.5  8.4  10.7  13.0  13.4  12.4  12.4
12  0  4.5  6.2  8.4  10.8  13.1  13.6  13.0  13.0
13  0  3.9  5.7  8.4  10.5  13.3  14.3  13.2  13.2
14  0  3.3  4.8  7.4   9.5  13.4  14.8  13.1  13.1
15  0  2.6  3.7  6.0   7.9  11.4  13.8  12.1  12.1
16  0  2.2  3.1  5.0   6.5   8.6  10.8  10.6  10.6
17  0  2.0  3.0  4.5   6.0   8.0   9.0  10.0  10.0
18  0  2.0  3.0  4.5   6.0   8.0   9.0  10.0  10.0