In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import inputs.vents as v
import inputs.courants as c
import inputs.polaires as p
import core.isochrone as iso

# Vent

In [64]:
path = "data/grib_vent/20260514_165330_GFS_P25_12.grb2"
df = v.table(path)
df

,latitude,longitude,valid_time,u10,v10,force,direction,temps,x_data,y_data
0,34.50,-14.75,2026-05-14 12:00:00,-2.626225,-9.193137,18.584862,15.943176,0.0,-619.5,2070.0
1,34.50,-14.50,2026-05-14 12:00:00,-1.846226,-8.143137,16.230682,12.774246,0.0,-609.0,2070.0
2,34.50,-14.25,2026-05-14 12:00:00,-0.706226,-7.223137,14.107575,5.584213,0.0,-598.5,2070.0
3,34.50,-14.00,2026-05-14 12:00:00,0.183774,-6.523137,12.684966,358.386230,0.0,-588.0,2070.0
4,34.50,-13.75,2026-05-14 12:00:00,0.873774,-6.013137,11.811336,351.732178,0.0,-577.5,2070.0
...,...,...,...,...,...,...,...,...,...,...
380047,51.25,1.25,2026-05-24 12:00:00,-3.999423,-2.235200,8.905993,60.800026,240.0,52.5,3075.0
380048,51.25,1.50,2026-05-24 12:00:00,-3.679423,-3.585200,9.986083,45.743103,240.0,63.0,3075.0
380049,51.25,1.75,2026-05-24 12:00:00,-3.859423,-3.835200,10.576331,45.180374,240.0,73.5,3075.0
380050,51.25,2.00,2026-05-24 12:00:00,-3.829423,-3.795200,10.480169,45.257172,240.0,84.0,3075.0
380051,51.25,2.25,2026-05-24 12:00:00,-3.699423,-4.175200,10.843427,41.542450,240.0,94.5,3075.0

In [65]:
VENT_NM = v.vent_grib_nm(path)
VENT_DEG = v.vent_grib_deg(path)

# Courant

In [5]:
path = "data/grib_courant/Hycom_Manche_Atlantique_120H.grb"
df = c.table(path)
df

,date,step_h,lat,lon,u_current,v_current,speed_ms,direction,x_data,y_data
0,20260514,0,43.008675,-15.000,-0.060821,0.035151,0.070248,300.025757,-630.00,2580.5205
1,20260514,0,43.008675,-14.975,-0.092071,0.035151,0.098553,290.896148,-628.95,2580.5205
2,20260514,0,43.008675,-14.950,-0.060821,0.003901,0.060946,273.670122,-627.90,2580.5205
3,20260514,0,43.008675,-14.925,0.001679,0.003901,0.004247,23.291076,-626.85,2580.5205
4,20260514,0,43.008675,-14.900,0.032929,0.003901,0.033160,83.243498,-625.80,2580.5205
...,...,...,...,...,...,...,...,...,...,...
40694395,20260514,119,51.000085,2.875,0.000000,0.000000,0.000000,0.000000,120.75,3060.0051
40694396,20260514,119,51.000085,2.900,0.000000,0.000000,0.000000,0.000000,121.80,3060.0051
40694397,20260514,119,51.000085,2.925,0.000000,0.000000,0.000000,0.000000,122.85,3060.0051
40694398,20260514,119,51.000085,2.950,0.000000,0.000000,0.000000,0.000000,123.90,3060.0051
40694399,20260514,119,51.000085,2.975,0.000000,0.000000,0.000000,0.000000,124.95,3060.0051

In [6]:
COURANT_NM = c.courant_grib_nm(path)
COURANT_DEG = c.courant_grib_deg(path)

# Polaire

In [9]:
path = "data/polaires/vector.csv"
POLAIRE = p.polaire(path)

# Routage

In [10]:
%matplotlib qt

In [11]:
# AFFICHAGE VENT

from matplotlib.widgets import Slider
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from datetime import datetime, timedelta

# -------------------------
# Paramètres de la grille
# -------------------------
inty = [min(pd.unique(df['latitude'])), max(pd.unique(df['latitude']))]
intx = [min(pd.unique(df['longitude'])), max(pd.unique(df['longitude']))]
intt = [0, max(pd.unique(df['temps']))]
n = 100

start_date = df['valid_time'][0]

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)
X, Y = np.meshgrid(lon, lat)

# Points de grille aplatis, réutilisés à chaque appel slider
pts_grid = np.column_stack([X.ravel(), Y.ravel()])  # ((n+1)², 2)

# -------------------------
# Initialisation figure
# -------------------------
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)

gl = ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                  linestyle='--', alpha=0.6)
gl.top_labels = False
gl.right_labels = False

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# -------------------------
# Fonction pour calculer vent (vectorisée)
# -------------------------
def compute_wind(t):
    wind = VENT_DEG(pts_grid, t)          # un seul appel batch → ((n+1)², 2)
    direction = wind[:, 0].reshape(X.shape)
    speed     = wind[:, 1].reshape(X.shape)
    U  = -speed * np.sin(np.radians(direction))
    Vv = -speed * np.cos(np.radians(direction))
    C  = np.clip(speed, 0, 20)
    return U, Vv, C

# -------------------------
# Vent initial
# -------------------------
initial_time = intt[0]
U, Vv, C = compute_wind(initial_time)
q = ax.quiver(X, Y, U, Vv, C, transform=ccrs.PlateCarree(), cmap='Greys')

# -------------------------
# Slider
# -------------------------
ax_slider = plt.axes([0.2, 0.02, 0.6, 0.03])
slider = Slider(ax_slider, 'Temps', valmin=intt[0], valmax=intt[1],
                valinit=intt[0], valstep=1, facecolor='grey')
slider.vline.set_visible(False)
slider.valtext.set_text((start_date + timedelta(hours=initial_time)).strftime("%d/%m %H:%M"))

def update(val):
    t = slider.val
    U, Vv, C = compute_wind(t)
    q.set_UVC(U, Vv, C)
    slider.valtext.set_text((start_date + timedelta(hours=t)).strftime("%d/%m %H:%M"))
    fig.canvas.draw_idle()

slider.on_changed(update)
plt.show()

In [9]:
import cProfile
import core.isochrone as iso

## N Isochrones

In [7]:
N = 99
p_dep = [50.15, -12.41]
p_arr = [43.71, -2.07]
p_dep = [p_dep[1] * 60 * 0.7, p_dep[0] * 60, 0, 0]
p_arr = [p_arr[1] * 60 * 0.7, p_arr[0] * 60]
t = 0
dt = 0.5
n = 100
r = POLAIRE.v_max * dt * 2 * np.pi / n
ang = np.pi/2
dang = np.radians(0.3)
delta = r
V = VENT_NM
P = POLAIRE

L = iso.n_iso(N, p_dep, p_arr, t, dt, n, V, P, r, ang, dang, C=None)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 0.50 heures, nombre de points : 100
nombre isochrones : 2, temps écoulé : 1.00 heures, nombre de points : 120
nombre isochrones : 3, temps écoulé : 1.50 heures, nombre de points : 179
nombre isochrones : 4, temps écoulé : 2.00 heures, nombre de points : 234
nombre isochrones : 5, temps écoulé : 2.50 heures, nombre de points : 292
nombre isochrones : 6, temps écoulé : 3.00 heures, nombre de points : 350
nombre isochrones : 7, temps écoulé : 3.50 heures, nombre de points : 404
nombre isochrones : 8, temps écoulé : 4.00 heures, nombre de points : 460
nombre isochrones : 9, temps écoulé : 4.50 heures, nombre de points : 516
nombre isochrones : 10, temps écoulé : 5.00 heures, nombre de points : 570
nombre isochrones : 11, temps écoulé : 5.50 heures, nombre de points : 626
nombre isochrones : 12, temps écoulé : 6.00 heures, nombre de points : 682
nombre isochrones : 13, temps écoulé : 6.50 heures, nombre de points : 737
nombre isochrones : 14, temps écoulé : 7.00 heures, nombre de points : 794
nombre isochrones : 15, temps écoulé : 7.50 heures, nombre de points : 851
nombre isochrones : 16, temps écoulé : 8.00 heures, nombre de points : 906
nombre isochrones : 17, temps écoulé : 8.50 heures, nombre de points : 959
nombre isochrones : 18, temps écoulé : 9.00 heures, nombre de points : 1013
nombre isochrones : 19, temps écoulé : 9.50 heures, nombre de points : 1065
nombre isochrones : 20, temps écoulé : 10.00 heures, nombre de points : 1116
nombre isochrones : 21, temps écoulé : 10.50 heures, nombre de points : 1171
nombre isochrones : 22, temps écoulé : 11.00 heures, nombre de points : 1223
nombre isochrones : 23, temps écoulé : 11.50 heures, nombre de points : 1279
nombre isochrones : 24, temps écoulé : 12.00 heures, nombre de points : 1335
nombre isochrones : 25, temps écoulé : 12.50 heures, nombre de points : 1387
nombre isochrones : 26, temps écoulé : 13.00 heures, nombre de points : 1449
nombre isochrones : 27, temps écoulé : 13.50 heures, nombre de points : 1510
nombre isochrones : 28, temps écoulé : 14.00 heures, nombre de points : 1574
nombre isochrones : 29, temps écoulé : 14.50 heures, nombre de points : 1659
nombre isochrones : 30, temps écoulé : 15.00 heures, nombre de points : 1719
nombre isochrones : 31, temps écoulé : 15.50 heures, nombre de points : 1803
nombre isochrones : 32, temps écoulé : 16.00 heures, nombre de points : 1885
nombre isochrones : 33, temps écoulé : 16.50 heures, nombre de points : 1961
nombre isochrones : 34, temps écoulé : 17.00 heures, nombre de points : 2026
nombre isochrones : 35, temps écoulé : 17.50 heures, nombre de points : 2104
nombre isochrones : 36, temps écoulé : 18.00 heures, nombre de points : 2185
nombre isochrones : 37, temps écoulé : 18.50 heures, nombre de points : 2262
nombre isochrones : 38, temps écoulé : 19.00 heures, nombre de points : 2317
nombre isochrones : 39, temps écoulé : 19.50 heures, nombre de points : 2387
nombre isochrones : 40, temps écoulé : 20.00 heures, nombre de points : 2461
nombre isochrones : 41, temps écoulé : 20.50 heures, nombre de points : 2538
nombre isochrones : 42, temps écoulé : 21.00 heures, nombre de points : 2590
nombre isochrones : 43, temps écoulé : 21.50 heures, nombre de points : 2663
nombre isochrones : 44, temps écoulé : 22.00 heures, nombre de points : 2738
nombre isochrones : 45, temps écoulé : 22.50 heures, nombre de points : 2796
nombre isochrones : 46, temps écoulé : 23.00 heures, nombre de points : 2868
nombre isochrones : 47, temps écoulé : 23.50 heures, nombre de points : 2985
nombre isochrones : 48, temps écoulé : 24.00 heures, nombre de points : 3100
nombre isochrones : 49, temps écoulé : 24.50 heures, nombre de points : 3117
nombre isochrones : 50, temps écoulé : 25.00 heures, nombre de points : 3241
nombre isochrones : 51, temps écoulé : 25.50 heures, nombre de points : 3371
nombre isochrones : 52, temps écoulé : 26.00 heures, nombre de points : 3497
nombre isochrones : 53, temps écoulé : 26.50 heures, nombre de points : 3607
nombre isochrones : 54, temps écoulé : 27.00 heures, nombre de points : 3729
nombre isochrones : 55, temps écoulé : 27.50 heures, nombre de points : 3878
nombre isochrones : 56, temps écoulé : 28.00 heures, nombre de points : 4068
nombre isochrones : 57, temps écoulé : 28.50 heures, nombre de points : 4263
nombre isochrones : 58, temps écoulé : 29.00 heures, nombre de points : 4431
nombre isochrones : 59, temps écoulé : 29.50 heures, nombre de points : 4597
nombre isochrones : 60, temps écoulé : 30.00 heures, nombre de points : 4752
nombre isochrones : 61, temps écoulé : 30.50 heures, nombre de points : 4947
nombre isochrones : 62, temps écoulé : 31.00 heures, nombre de points : 5104
nombre isochrones : 63, temps écoulé : 31.50 heures, nombre de points : 5267
nombre isochrones : 64, temps écoulé : 32.00 heures, nombre de points : 5390
nombre isochrones : 65, temps écoulé : 32.50 heures, nombre de points : 5548
nombre isochrones : 66, temps écoulé : 33.00 heures, nombre de points : 5704
nombre isochrones : 67, temps écoulé : 33.50 heures, nombre de points : 5926
nombre isochrones : 68, temps écoulé : 34.00 heures, nombre de points : 6061
nombre isochrones : 69, temps écoulé : 34.50 heures, nombre de points : 6244
nombre isochrones : 70, temps écoulé : 35.00 heures, nombre de points : 6379
nombre isochrones : 71, temps écoulé : 35.50 heures, nombre de points : 6563
nombre isochrones : 72, temps écoulé : 36.00 heures, nombre de points : 6692
nombre isochrones : 73, temps écoulé : 36.50 heures, nombre de points : 6838
nombre isochrones : 74, temps écoulé : 37.00 heures, nombre de points : 7016
nombre isochrones : 75, temps écoulé : 37.50 heures, nombre de points : 7096
nombre isochrones : 76, temps écoulé : 38.00 heures, nombre de points : 7230
nombre isochrones : 77, temps écoulé : 38.50 heures, nombre de points : 7381
nombre isochrones : 78, temps écoulé : 39.00 heures, nombre de points : 7553
nombre isochrones : 79, temps écoulé : 39.50 heures, nombre de points : 7695
nombre isochrones : 80, temps écoulé : 40.00 heures, nombre de points : 7855
nombre isochrones : 81, temps écoulé : 40.50 heures, nombre de points : 7980
nombre isochrones : 82, temps écoulé : 41.00 heures, nombre de points : 8085
nombre isochrones : 83, temps écoulé : 41.50 heures, nombre de points : 8252
nombre isochrones : 84, temps écoulé : 42.00 heures, nombre de points : 8431
nombre isochrones : 85, temps écoulé : 42.50 heures, nombre de points : 8628
nombre isochrones : 86, temps écoulé : 43.00 heures, nombre de points : 8802
nombre isochrones : 87, temps écoulé : 43.50 heures, nombre de points : 8952
nombre isochrones : 88, temps écoulé : 44.00 heures, nombre de points : 9109
nombre isochrones : 89, temps écoulé : 44.50 heures, nombre de points : 9270
nombre isochrones : 90, temps écoulé : 45.00 heures, nombre de points : 9459
nombre isochrones : 91, temps écoulé : 45.50 heures, nombre de points : 9294
nombre isochrones : 92, temps écoulé : 46.00 heures, nombre de points : 9385
nombre isochrones : 93, temps écoulé : 46.50 heures, nombre de points : 9456
nombre isochrones : 94, temps écoulé : 47.00 heures, nombre de points : 9534
nombre isochrones : 95, temps écoulé : 47.50 heures, nombre de points : 9564
nombre isochrones : 96, temps écoulé : 48.00 heures, nombre de points : 9671
nombre isochrones : 97, temps écoulé : 48.50 heures, nombre de points : 9779
nombre isochrones : 98, temps écoulé : 49.00 heures, nombre de points : 9850
nombre isochrones : 99, temps écoulé : 49.50 heures, nombre de points : 9928

In [17]:
plt.scatter(L[:, 0], L[:, 1], c = 'blue')
plt.scatter([p_arr[0]], [p_arr[1]], c = 'red')
plt.axis('equal')

(np.float64(-657.1975727815827),
 np.float64(48.993337085880114),
 np.float64(2436.714990260405),
 np.float64(3108.9371101268325))

In [8]:
I = L[L[:, 2] == 99]

In [9]:
t = 49.5
dt = 0.5
n = 100
N = iso.nuage_iso(I, t, dt, n, V, P)

In [10]:
import core.enveloppe as env
ang = np.pi/2 - 99 * np.radians(0.3)
E = env.enveloppe(N, r, p_dep, p_arr, ang, delta)

In [26]:
import core.utils as f
from scipy.spatial import cKDTree
p_dep = np.array(p_dep, dtype=float)
p_arr = np.array(p_arr, dtype=float)
dir = f.angle_direction(p_dep, p_arr)
p1, p = env.points_les_plus_a(N, dir + ang, p_dep, delta)

#voisins1 = pointsautour_np(p1, P, r)
tree = cKDTree(N[:, :2])
voisins1 = N[tree.query_ball_point(p1[:2], r)]

#angles1 = np.abs(np.array([f.angleoriente3_np(p, p1, x) for x in voisins1]))
angles1 = f.angle_oriente_positif(p, p1, voisins1)

# gestion cas 2 angles égaux
max_angle = np.max(angles1)
eps = 1e-12
candidats = np.where(np.abs(angles1 - max_angle) < eps)[0]
if len(candidats) == 1:
    idx = candidats[0]
else:
    dists = np.linalg.norm(voisins1[candidats, :2] - p1[:2], axis=1)
    idx = candidats[np.argmin(dists)]

p2 = voisins1[idx]

max_points = 10000   # borne large mais sûre
l = np.empty((max_points, N.shape[1]))
l[0] = p
l[1] = p1
l[2] = p2
k = 3

#l = [p, p1, p2]

#while not np.array_equal(p2, l[0]): 
angle_g = f.angle_oriente_negatif(l[1], p_dep, p_arr)
angle_oriente = f.angle_oriente_negatif(l[1], p_dep, l[k-1])

In [48]:
for _ in range(1000):
    #voisins = pointsautour_np(p2, P, r)
    voisins = N[tree.query_ball_point(p2[:2], r)]
    #angles = np.abs(np.array([f.angleoriente3_np(p1, p2, x) for x in voisins]))
    angles = f.angle_oriente_positif(p1, p2, voisins)

    # gestion cas 2 angles égaux
    max_angle = np.max(angles)
    candidats = np.where(np.abs(angles - max_angle) < eps)[0]
    if len(candidats) == 1:
        idx = candidats[0]
    else:
        dists = np.linalg.norm(voisins[candidats, :2] - p2[:2], axis=1)
        idx = candidats[np.argmin(dists)]

    p3 = voisins[idx]

    if max_angle > np.pi:

        while env.bouclage(l[:k], p3):
        # while bouclage(np.array(l), p3):
            mask = np.ones(len(voisins), dtype=bool)
            mask[idx] = False
            voisins = voisins[mask]
            angles = angles[mask]
            #voisins = np.delete(voisins, idx, axis=0)
            #angles = np.delete(angles, idx)
            if voisins.size == 0:
                raise ValueError(f"Aucun voisin trouvé dans le cercle r.")

            # gestion cas 2 angles égaux
            max_angle = np.max(angles)
            candidats = np.where(np.abs(angles - max_angle) < eps)[0]
            if len(candidats) == 1:
                idx = candidats[0]
            else:
                dists = np.linalg.norm(voisins[candidats, :2] - p2[:2], axis=1)
                idx = candidats[np.argmin(dists)]

            p3 = voisins[idx]

    l[k] = p3
    k += 1
    p1, p2 = p2, p3
    angle_oriente = f.angle_oriente_negatif(l[1], p_dep, l[k-1])

IndexError: index 10000 is out of bounds for axis 0 with size 10000

In [49]:
plt.scatter(N[:, 0], N[:, 1], c = 'grey')
plt.scatter(I[:, 0], I[:, 1], c = 'blue')
plt.scatter(l[:k][:, 0], l[:k][:, 1], c = 'red')
plt.axis('equal')

(np.float64(-654.677827914912),
 np.float64(52.226400921357126),
 np.float64(2432.0680551878836),
 np.float64(3109.1583927493334))

## Routage complet

In [86]:
p_dep = [45, -4]
p_arr = [46, -10]
p_dep = [p_dep[1] * 60 * 0.7, p_dep[0] * 60, 0, 0]
p_arr = [p_arr[1] * 60 * 0.7, p_arr[0] * 60]
t = 0
dt = 1
n = 100
e_arr = P.v_max * dt / 2
r = POLAIRE.v_max * dt * 2 * np.pi / n
ang = np.pi/2
dang = 0
delta = r
V = VENT_NM
P = POLAIRE

routage = iso.toutes_iso(p_dep, p_arr, t, dt, n, V, P, e_arr, r, ang, dang)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 1.00 heures, nombre de points : 43
nombre isochrones : 2, temps : 2.00 heures, nombre de points : 75
nombre isochrones : 3, temps : 3.00 heures, nombre de points : 110
nombre isochrones : 4, temps : 4.00 heures, nombre de points : 142
nombre isochrones : 5, temps : 5.00 heures, nombre de points : 176
nombre isochrones : 6, temps : 6.00 heures, nombre de points : 209
nombre isochrones : 7, temps : 7.00 heures, nombre de points : 251
nombre isochrones : 8, temps : 8.00 heures, nombre de points : 286
nombre isochrones : 9, temps : 9.00 heures, nombre de points : 322
nombre isochrones : 10, temps : 10.00 heures, nombre de points : 363
nombre isochrones : 11, temps : 11.00 heures, nombre de points : 402
nombre isochrones : 12, temps : 12.00 heures, nombre de points : 430
nombre isochrones : 13, temps : 13.00 heures, nombre de points : 456
nombre isochrones : 14, temps : 14.00 heures, nombre de points : 490
nombre isochrones : 15, temps : 15.00 heures, nombre de points : 527
nombre isochrones : 16, temps : 16.00 heures, nombre de points : 562
nombre isochrones : 17, temps : 17.00 heures, nombre de points : 605
nombre isochrones : 18, temps : 18.00 heures, nombre de points : 648
nombre isochrones : 19, temps : 19.00 heures, nombre de points : 712
nombre isochrones : 20, temps : 20.00 heures, nombre de points : 755
nombre isochrones : 21, temps : 21.00 heures, nombre de points : 794
nombre isochrones : 22, temps : 22.00 heures, nombre de points : 843
nombre isochrones : 23, temps : 23.00 heures, nombre de points : 897
nombre isochrones : 24, temps : 24.00 heures, nombre de points : 959
nombre isochrones : 25, temps : 25.00 heures, nombre de points : 1033
nombre isochrones : 26, temps : 26.00 heures, nombre de points : 1092
nombre isochrones : 27, temps : 27.00 heures, nombre de points : 1156
nombre isochrones : 28, temps : 28.00 heures, nombre de points : 1218
nombre isochrones : 29, temps : 29.00 heures, nombre de points : 1275
nombre isochrones : 30, temps : 30.00 heures, nombre de points : 1334
nombre isochrones : 31, temps : 31.00 heures, nombre de points : 1397
nombre isochrones : 32, temps : 32.00 heures, nombre de points : 1470
nombre isochrones : 33, temps : 33.00 heures, nombre de points : 1567
nombre isochrones : 34, temps : 34.00 heures, nombre de points : 1648
nombre isochrones : 35, temps : 35.00 heures, nombre de points : 1732
nombre isochrones : 36, temps : 36.00 heures, nombre de points : 1829
nombre isochrones : 37, temps : 37.00 heures, nombre de points : 1962
nombre isochrones : 38, temps : 38.00 heures, nombre de points : 2097
nombre isochrones : 39, temps : 39.00 heures, nombre de points : 2178
nombre isochrones : 40, temps : 40.00 heures, nombre de points : 2294
nombre isochrones : 41, temps : 41.00 heures, nombre de points : 2448

In [87]:
L, route, time_list = routage

t_arr = time_list[-1]
print((t_arr - t) // 24, "jours", (t_arr - t) % 24, "heures")

1 jours 17 heures

In [88]:
plt.scatter(L[:, 0], L[:, 1], c = 'blue')
plt.scatter(route[:, 0], route[:, 1], c = 'red')
plt.axis('equal')

(np.float64(-541.5480101818454),
 np.float64(-108.07704312978785),
 np.float64(2465.6473423757625),
 np.float64(2931.6877695622356))

In [90]:
VENT_NM_RED = v.vent_filtre_route(VENT_NM, route, 10)

In [91]:
N = 100
p_dep = [45, -4]
p_arr = [46, -10]
p_dep = [p_dep[1] * 60 * 0.7, p_dep[0] * 60, 0, 0]
p_arr = [p_arr[1] * 60 * 0.7, p_arr[0] * 60]
t = 0
dt = 0.25
n = 100
r = POLAIRE.v_max * dt * 2 * np.pi / n
ang = np.pi/2
dang = np.radians(0.3)
delta = r
V = VENT_NM_RED
P = POLAIRE

L = iso.n_iso(N, p_dep, p_arr, t, dt, n, V, P, r, ang, dang)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 0.25 heures, nombre de points : 100
nombre isochrones : 2, temps écoulé : 0.50 heures, nombre de points : 75
nombre isochrones : 3, temps écoulé : 0.75 heures, nombre de points : 111
nombre isochrones : 4, temps écoulé : 1.00 heures, nombre de points : 145
nombre isochrones : 5, temps écoulé : 1.25 heures, nombre de points : 170
nombre isochrones : 6, temps écoulé : 1.50 heures, nombre de points : 187
nombre isochrones : 7, temps écoulé : 1.75 heures, nombre de points : 204
nombre isochrones : 8, temps écoulé : 2.00 heures, nombre de points : 215
nombre isochrones : 9, temps écoulé : 2.25 heures, nombre de points : 227
nombre isochrones : 10, temps écoulé : 2.50 heures, nombre de points : 238
nombre isochrones : 11, temps écoulé : 2.75 heures, nombre de points : 247
nombre isochrones : 12, temps écoulé : 3.00 heures, nombre de points : 258
nombre isochrones : 13, temps écoulé : 3.25 heures, nombre de points : 269
nombre isochrones : 14, temps écoulé : 3.50 heures, nombre de points : 280
nombre isochrones : 15, temps écoulé : 3.75 heures, nombre de points : 288
nombre isochrones : 16, temps écoulé : 4.00 heures, nombre de points : 297
nombre isochrones : 17, temps écoulé : 4.25 heures, nombre de points : 306
nombre isochrones : 18, temps écoulé : 4.50 heures, nombre de points : 314
nombre isochrones : 19, temps écoulé : 4.75 heures, nombre de points : 320
nombre isochrones : 20, temps écoulé : 5.00 heures, nombre de points : 327
nombre isochrones : 21, temps écoulé : 5.25 heures, nombre de points : 334
nombre isochrones : 22, temps écoulé : 5.50 heures, nombre de points : 344
nombre isochrones : 23, temps écoulé : 5.75 heures, nombre de points : 360
nombre isochrones : 24, temps écoulé : 6.00 heures, nombre de points : 379
nombre isochrones : 25, temps écoulé : 6.25 heures, nombre de points : 402
nombre isochrones : 26, temps écoulé : 6.50 heures, nombre de points : 421
nombre isochrones : 27, temps écoulé : 6.75 heures, nombre de points : 441
nombre isochrones : 28, temps écoulé : 7.00 heures, nombre de points : 469
nombre isochrones : 29, temps écoulé : 7.25 heures, nombre de points : 487
nombre isochrones : 30, temps écoulé : 7.50 heures, nombre de points : 500
nombre isochrones : 31, temps écoulé : 7.75 heures, nombre de points : 506
nombre isochrones : 32, temps écoulé : 8.00 heures, nombre de points : 524
nombre isochrones : 33, temps écoulé : 8.25 heures, nombre de points : 541
nombre isochrones : 34, temps écoulé : 8.50 heures, nombre de points : 561
nombre isochrones : 35, temps écoulé : 8.75 heures, nombre de points : 578
nombre isochrones : 36, temps écoulé : 9.00 heures, nombre de points : 598
nombre isochrones : 37, temps écoulé : 9.25 heures, nombre de points : 618
nombre isochrones : 38, temps écoulé : 9.50 heures, nombre de points : 638
nombre isochrones : 39, temps écoulé : 9.75 heures, nombre de points : 657
nombre isochrones : 40, temps écoulé : 10.00 heures, nombre de points : 676
nombre isochrones : 41, temps écoulé : 10.25 heures, nombre de points : 694
nombre isochrones : 42, temps écoulé : 10.50 heures, nombre de points : 715
nombre isochrones : 43, temps écoulé : 10.75 heures, nombre de points : 732
nombre isochrones : 44, temps écoulé : 11.00 heures, nombre de points : 753
nombre isochrones : 45, temps écoulé : 11.25 heures, nombre de points : 777
nombre isochrones : 46, temps écoulé : 11.50 heures, nombre de points : 802
nombre isochrones : 47, temps écoulé : 11.75 heures, nombre de points : 832
nombre isochrones : 48, temps écoulé : 12.00 heures, nombre de points : 860
nombre isochrones : 49, temps écoulé : 12.25 heures, nombre de points : 889
nombre isochrones : 50, temps écoulé : 12.50 heures, nombre de points : 915
nombre isochrones : 51, temps écoulé : 12.75 heures, nombre de points : 944
nombre isochrones : 52, temps écoulé : 13.00 heures, nombre de points : 973
nombre isochrones : 53, temps écoulé : 13.25 heures, nombre de points : 1000
nombre isochrones : 54, temps écoulé : 13.50 heures, nombre de points : 1028
nombre isochrones : 55, temps écoulé : 13.75 heures, nombre de points : 1056
nombre isochrones : 56, temps écoulé : 14.00 heures, nombre de points : 1085
nombre isochrones : 57, temps écoulé : 14.25 heures, nombre de points : 1118
nombre isochrones : 58, temps écoulé : 14.50 heures, nombre de points : 1149
nombre isochrones : 59, temps écoulé : 14.75 heures, nombre de points : 1178
nombre isochrones : 60, temps écoulé : 15.00 heures, nombre de points : 1212
nombre isochrones : 61, temps écoulé : 15.25 heures, nombre de points : 1241
nombre isochrones : 62, temps écoulé : 15.50 heures, nombre de points : 1275
nombre isochrones : 63, temps écoulé : 15.75 heures, nombre de points : 1307
nombre isochrones : 64, temps écoulé : 16.00 heures, nombre de points : 1341
nombre isochrones : 65, temps écoulé : 16.25 heures, nombre de points : 1375
nombre isochrones : 66, temps écoulé : 16.50 heures, nombre de points : 1407
nombre isochrones : 67, temps écoulé : 16.75 heures, nombre de points : 1441
nombre isochrones : 68, temps écoulé : 17.00 heures, nombre de points : 1477
nombre isochrones : 69, temps écoulé : 17.25 heures, nombre de points : 1512
nombre isochrones : 70, temps écoulé : 17.50 heures, nombre de points : 1548
nombre isochrones : 71, temps écoulé : 17.75 heures, nombre de points : 1581
nombre isochrones : 72, temps écoulé : 18.00 heures, nombre de points : 1618
nombre isochrones : 73, temps écoulé : 18.25 heures, nombre de points : 1656
nombre isochrones : 74, temps écoulé : 18.50 heures, nombre de points : 1693
nombre isochrones : 75, temps écoulé : 18.75 heures, nombre de points : 1730
nombre isochrones : 76, temps écoulé : 19.00 heures, nombre de points : 1768
nombre isochrones : 77, temps écoulé : 19.25 heures, nombre de points : 1808
nombre isochrones : 78, temps écoulé : 19.50 heures, nombre de points : 1844
nombre isochrones : 79, temps écoulé : 19.75 heures, nombre de points : 1880
nombre isochrones : 80, temps écoulé : 20.00 heures, nombre de points : 1918
nombre isochrones : 81, temps écoulé : 20.25 heures, nombre de points : 1953
nombre isochrones : 82, temps écoulé : 20.50 heures, nombre de points : 1989
nombre isochrones : 83, temps écoulé : 20.75 heures, nombre de points : 2025
nombre isochrones : 84, temps écoulé : 21.00 heures, nombre de points : 2059
nombre isochrones : 85, temps écoulé : 21.25 heures, nombre de points : 2095
nombre isochrones : 86, temps écoulé : 21.50 heures, nombre de points : 2131
nombre isochrones : 87, temps écoulé : 21.75 heures, nombre de points : 2166
nombre isochrones : 88, temps écoulé : 22.00 heures, nombre de points : 2206
nombre isochrones : 89, temps écoulé : 22.25 heures, nombre de points : 2240
nombre isochrones : 90, temps écoulé : 22.50 heures, nombre de points : 2273
nombre isochrones : 91, temps écoulé : 22.75 heures, nombre de points : 2306
nombre isochrones : 92, temps écoulé : 23.00 heures, nombre de points : 2342
nombre isochrones : 93, temps écoulé : 23.25 heures, nombre de points : 2380
nombre isochrones : 94, temps écoulé : 23.50 heures, nombre de points : 2416
nombre isochrones : 95, temps écoulé : 23.75 heures, nombre de points : 2449
nombre isochrones : 96, temps écoulé : 24.00 heures, nombre de points : 2481
nombre isochrones : 97, temps écoulé : 24.25 heures, nombre de points : 2513
nombre isochrones : 98, temps écoulé : 24.50 heures, nombre de points : 2547
nombre isochrones : 99, temps écoulé : 24.75 heures, nombre de points : 2578
nombre isochrones : 100, temps écoulé : 25.00 heures, nombre de points : 2611

In [92]:
plt.scatter(L[:, 0], L[:, 1], c = 'blue')
plt.axis('equal')

(np.float64(-356.2897365968224),
 np.float64(-153.89327343296085),
 np.float64(2684.3067433038987),
 np.float64(2747.556903692461))

In [93]:
N = 100
p_dep = [45, -4]
p_arr = [46, -10]
p_dep = [p_dep[1] * 60 * 0.7, p_dep[0] * 60, 0, 0]
p_arr = [p_arr[1] * 60 * 0.7, p_arr[0] * 60]
t = 0
dt = 1
n = 100
r = POLAIRE.v_max * dt * 2 * np.pi / n
ang = np.pi/2
dang = np.radians(0.3)
delta = r
V = VENT_NM
P = POLAIRE

L = iso.n_iso(N, p_dep, p_arr, t, dt, n, V, P, r, ang, dang)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1
nombre isochrones : 1, temps : 1.00 heures, nombre de points : 100
nombre isochrones : 2, temps écoulé : 2.00 heures, nombre de points : 75
nombre isochrones : 3, temps écoulé : 3.00 heures, nombre de points : 109
nombre isochrones : 4, temps écoulé : 4.00 heures, nombre de points : 141
nombre isochrones : 5, temps écoulé : 5.00 heures, nombre de points : 172
nombre isochrones : 6, temps écoulé : 6.00 heures, nombre de points : 204
nombre isochrones : 7, temps écoulé : 7.00 heures, nombre de points : 244
nombre isochrones : 8, temps écoulé : 8.00 heures, nombre de points : 276
nombre isochrones : 9, temps écoulé : 9.00 heures, nombre de points : 312
nombre isochrones : 10, temps écoulé : 10.00 heures, nombre de points : 350
nombre isochrones : 11, temps écoulé : 11.00 heures, nombre de points : 385
nombre isochrones : 12, temps écoulé : 12.00 heures, nombre de points : 413
nombre isochrones : 13, temps écoulé : 13.00 heures, nombre de points : 437
nombre isochrones : 14, temps écoulé : 14.00 heures, nombre de points : 469
nombre isochrones : 15, temps écoulé : 15.00 heures, nombre de points : 504
nombre isochrones : 16, temps écoulé : 16.00 heures, nombre de points : 538
nombre isochrones : 17, temps écoulé : 17.00 heures, nombre de points : 578
nombre isochrones : 18, temps écoulé : 18.00 heures, nombre de points : 616
nombre isochrones : 19, temps écoulé : 19.00 heures, nombre de points : 680
nombre isochrones : 20, temps écoulé : 20.00 heures, nombre de points : 723
nombre isochrones : 21, temps écoulé : 21.00 heures, nombre de points : 758
nombre isochrones : 22, temps écoulé : 22.00 heures, nombre de points : 803
nombre isochrones : 23, temps écoulé : 23.00 heures, nombre de points : 850
nombre isochrones : 24, temps écoulé : 24.00 heures, nombre de points : 908
nombre isochrones : 25, temps écoulé : 25.00 heures, nombre de points : 977
nombre isochrones : 26, temps écoulé : 26.00 heures, nombre de points : 1036
nombre isochrones : 27, temps écoulé : 27.00 heures, nombre de points : 1091
nombre isochrones : 28, temps écoulé : 28.00 heures, nombre de points : 1140
nombre isochrones : 29, temps écoulé : 29.00 heures, nombre de points : 1202
nombre isochrones : 30, temps écoulé : 30.00 heures, nombre de points : 1260
nombre isochrones : 31, temps écoulé : 31.00 heures, nombre de points : 1318
nombre isochrones : 32, temps écoulé : 32.00 heures, nombre de points : 1384
nombre isochrones : 33, temps écoulé : 33.00 heures, nombre de points : 1472
nombre isochrones : 34, temps écoulé : 34.00 heures, nombre de points : 1564
nombre isochrones : 35, temps écoulé : 35.00 heures, nombre de points : 1641
nombre isochrones : 36, temps écoulé : 36.00 heures, nombre de points : 1733
nombre isochrones : 37, temps écoulé : 37.00 heures, nombre de points : 1871
nombre isochrones : 38, temps écoulé : 38.00 heures, nombre de points : 2000
nombre isochrones : 39, temps écoulé : 39.00 heures, nombre de points : 2061
nombre isochrones : 40, temps écoulé : 40.00 heures, nombre de points : 2125
nombre isochrones : 41, temps écoulé : 41.00 heures, nombre de points : 2283
nombre isochrones : 42, temps écoulé : 42.00 heures, nombre de points : 2382
nombre isochrones : 43, temps écoulé : 43.00 heures, nombre de points : 2475
nombre isochrones : 44, temps écoulé : 44.00 heures, nombre de points : 2579
nombre isochrones : 45, temps écoulé : 45.00 heures, nombre de points : 2708
nombre isochrones : 46, temps écoulé : 46.00 heures, nombre de points : 2812
nombre isochrones : 47, temps écoulé : 47.00 heures, nombre de points : 2591
nombre isochrones : 48, temps écoulé : 48.00 heures, nombre de points : 2635
nombre isochrones : 49, temps écoulé : 49.00 heures, nombre de points : 2668
nombre isochrones : 50, temps écoulé : 50.00 heures, nombre de points : 2718
nombre isochrones : 51, temps écoulé : 51.00 heures, nombre de points : 2749
nombre isochrones : 52, temps écoulé : 52.00 heures, nombre de points : 2791
nombre isochrones : 53, temps écoulé : 53.00 heures, nombre de points : 2845
nombre isochrones : 54, temps écoulé : 54.00 heures, nombre de points : 2905
nombre isochrones : 55, temps écoulé : 55.00 heures, nombre de points : 2972
nombre isochrones : 56, temps écoulé : 56.00 heures, nombre de points : 3064
nombre isochrones : 57, temps écoulé : 57.00 heures, nombre de points : 3137
nombre isochrones : 58, temps écoulé : 58.00 heures, nombre de points : 2002
nombre isochrones : 59, temps écoulé : 59.00 heures, nombre de points : 2075
nombre isochrones : 60, temps écoulé : 60.00 heures, nombre de points : 2161
nombre isochrones : 61, temps écoulé : 61.00 heures, nombre de points : 2058
nombre isochrones : 62, temps écoulé : 62.00 heures, nombre de points : 2108
nombre isochrones : 63, temps écoulé : 63.00 heures, nombre de points : 2150
nombre isochrones : 64, temps écoulé : 64.00 heures, nombre de points : 2171
nombre isochrones : 65, temps écoulé : 65.00 heures, nombre de points : 2211
nombre isochrones : 66, temps écoulé : 66.00 heures, nombre de points : 2251
nombre isochrones : 67, temps écoulé : 67.00 heures, nombre de points : 2272
nombre isochrones : 68, temps écoulé : 68.00 heures, nombre de points : 2300
nombre isochrones : 69, temps écoulé : 69.00 heures, nombre de points : 2340
nombre isochrones : 70, temps écoulé : 70.00 heures, nombre de points : 2356
nombre isochrones : 71, temps écoulé : 71.00 heures, nombre de points : 2397
nombre isochrones : 72, temps écoulé : 72.00 heures, nombre de points : 2430
nombre isochrones : 73, temps écoulé : 73.00 heures, nombre de points : 2448
nombre isochrones : 74, temps écoulé : 74.00 heures, nombre de points : 2470
nombre isochrones : 75, temps écoulé : 75.00 heures, nombre de points : 2479
nombre isochrones : 76, temps écoulé : 76.00 heures, nombre de points : 2491
nombre isochrones : 77, temps écoulé : 77.00 heures, nombre de points : 2514
nombre isochrones : 78, temps écoulé : 78.00 heures, nombre de points : 2536
nombre isochrones : 79, temps écoulé : 79.00 heures, nombre de points : 2563
nombre isochrones : 80, temps écoulé : 80.00 heures, nombre de points : 2591
nombre isochrones : 81, temps écoulé : 81.00 heures, nombre de points : 2619
nombre isochrones : 82, temps écoulé : 82.00 heures, nombre de points : 2657
nombre isochrones : 83, temps écoulé : 83.00 heures, nombre de points : 2690
nombre isochrones : 84, temps écoulé : 84.00 heures, nombre de points : 2743
nombre isochrones : 85, temps écoulé : 85.00 heures, nombre de points : 2789
nombre isochrones : 86, temps écoulé : 86.00 heures, nombre de points : 2819
nombre isochrones : 87, temps écoulé : 87.00 heures, nombre de points : 2842
nombre isochrones : 88, temps écoulé : 88.00 heures, nombre de points : 2867
nombre isochrones : 89, temps écoulé : 89.00 heures, nombre de points : 2870
nombre isochrones : 90, temps écoulé : 90.00 heures, nombre de points : 2850
nombre isochrones : 91, temps écoulé : 91.00 heures, nombre de points : 2857
nombre isochrones : 92, temps écoulé : 92.00 heures, nombre de points : 2866
nombre isochrones : 93, temps écoulé : 93.00 heures, nombre de points : 2865
nombre isochrones : 94, temps écoulé : 94.00 heures, nombre de points : 2868
nombre isochrones : 95, temps écoulé : 95.00 heures, nombre de points : 2868
nombre isochrones : 96, temps écoulé : 96.00 heures, nombre de points : 2853
nombre isochrones : 97, temps écoulé : 97.00 heures, nombre de points : 2831
nombre isochrones : 98, temps écoulé : 98.00 heures, nombre de points : 2815
nombre isochrones : 99, temps écoulé : 99.00 heures, nombre de points : 2795
nombre isochrones : 100, temps écoulé : 100.00 heures, nombre de points : 2770

In [94]:
plt.scatter(L[:, 0], L[:, 1], c = 'blue')
plt.axis('equal')

(np.float64(-656.9955296380776),
 np.float64(-129.1787943497103),
 np.float64(2084.0459962965997),
 np.float64(3136.6248064697725))

In [47]:
p_dep = [45, -4]
p_arr = [46, -10]
t = 0
dt = 1
n = 100
r = POLAIRE.v_max * dt * 2 * np.pi / n
ang = np.pi/2
dang = np.radians(0.3)
delta = r
V = VENT_NM
P = POLAIRE

routage = iso.routage(p_dep, p_arr, t, dt, n, V, P, ang, dang)

nombre isochrones : 0, temps : 0.00 heures, nombre de points : 1

IndexError: index 100000 is out of bounds for axis 0 with size 100000

In [14]:
latitude, longitude, time_list, L = routage

t_arr = time_list[-1]
print((t_arr - t) // 24, "jours", (t_arr - t) % 24, "heures")

1 jours 17 heures

In [42]:
# AFFICHAGE VENT

from matplotlib.widgets import Slider
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from datetime import datetime, timedelta

# -------------------------
# Paramètres de la grille
# -------------------------
inty = [min(pd.unique(df['latitude'])), max(pd.unique(df['latitude']))]
intx = [min(pd.unique(df['longitude'])), max(pd.unique(df['longitude']))]
intt = [0, max(pd.unique(df['temps']))]
n = 100

start_date = df['valid_time'][0]

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)
X, Y = np.meshgrid(lon, lat)

# Points de grille aplatis, réutilisés à chaque appel slider
pts_grid = np.column_stack([X.ravel(), Y.ravel()])  # ((n+1)², 2)

# -------------------------
# Initialisation figure
# -------------------------
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)

gl = ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                  linestyle='--', alpha=0.6)
gl.top_labels = False
gl.right_labels = False

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# -------------------------
# Fonction pour calculer vent (vectorisée)
# -------------------------
def compute_wind(t):
    wind = VENT_DEG(pts_grid, t)          # un seul appel batch → ((n+1)², 2)
    direction = wind[:, 0].reshape(X.shape)
    speed     = wind[:, 1].reshape(X.shape)
    U  = -speed * np.sin(np.radians(direction))
    Vv = -speed * np.cos(np.radians(direction))
    C  = np.clip(speed, 0, 20)
    return U, Vv, C

# -------------------------
# Vent initial
# -------------------------
initial_time = intt[0]
U, Vv, C = compute_wind(initial_time)
q = ax.quiver(X, Y, U, Vv, C, transform=ccrs.PlateCarree(), cmap='Greys')

# -------------------------
# Slider
# -------------------------
ax_slider = plt.axes([0.2, 0.02, 0.6, 0.03])
slider = Slider(ax_slider, 'Temps', valmin=intt[0], valmax=intt[1],
                valinit=intt[0], valstep=1, facecolor='grey')
slider.vline.set_visible(False)
slider.valtext.set_text((start_date + timedelta(hours=initial_time)).strftime("%d/%m %H:%M"))

def update(val):
    t = slider.val
    U, Vv, C = compute_wind(t)
    q.set_UVC(U, Vv, C)
    slider.valtext.set_text((start_date + timedelta(hours=t)).strftime("%d/%m %H:%M"))
    fig.canvas.draw_idle()

slider.on_changed(update)
plt.show()

In [95]:
# AFFICHAGE VENT + ROUTE

from matplotlib.widgets import Slider
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from datetime import datetime, timedelta

# -------------------------
# Paramètres de la grille
# -------------------------
inty = [min(pd.unique(df['latitude'])), max(pd.unique(df['latitude']))]
intx = [min(pd.unique(df['longitude'])), max(pd.unique(df['longitude']))]
intt = [0, max(pd.unique(df['temps']))]
n = 100

start_date = df['valid_time'][0]

lon = np.linspace(intx[0], intx[1], n+1)
lat = np.linspace(inty[0], inty[1], n+1)
X, Y = np.meshgrid(lon, lat)

# Points de grille aplatis, réutilisés à chaque appel slider
pts_grid = np.column_stack([X.ravel(), Y.ravel()])  # ((n+1)², 2)

# -------------------------
# Initialisation figure
# -------------------------
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)

gl = ax.gridlines(draw_labels=True, crs=ccrs.PlateCarree(),
                  linestyle='--', alpha=0.6)
gl.top_labels = False
gl.right_labels = False

ax.set_extent([intx[0], intx[1], inty[0], inty[1]],
              crs=ccrs.PlateCarree())

# -------------------------
# Fonction pour calculer vent (vectorisée)
# -------------------------
def compute_wind(t):
    wind = VENT_DEG(pts_grid, t)          # un seul appel batch → ((n+1)², 2)
    direction = wind[:, 0].reshape(X.shape)
    speed     = wind[:, 1].reshape(X.shape)
    U  = -speed * np.sin(np.radians(direction))
    Vv = -speed * np.cos(np.radians(direction))
    C  = np.clip(speed, 0, 20)
    return U, Vv, C

# -------------------------
# Vent initial
# -------------------------
initial_time = intt[0]
U, Vv, C = compute_wind(initial_time)
q = ax.quiver(X, Y, U, Vv, C, transform=ccrs.PlateCarree(), cmap='Greys')

# -------------------------
# Route
# -------------------------
for i in range(len(latitude)):
    l = L[L[:, 2] == i]
    ax.plot(l[:, 1], l[:, 0], transform=ccrs.PlateCarree(), c='lightcoral')

route_line, = ax.plot(longitude, latitude, transform=ccrs.PlateCarree(), c='red')
boat_scatter = ax.scatter(longitude[0], latitude[0], c='red', transform=ccrs.PlateCarree())

# -------------------------
# Slider
# -------------------------
ax_slider = plt.axes([0.2, 0.02, 0.6, 0.03])
slider = Slider(ax_slider, 'Temps', valmin=intt[0], valmax=intt[1],
                valinit=intt[0], valstep=1, facecolor='grey')
slider.vline.set_visible(False)
slider.valtext.set_text((start_date + timedelta(hours=initial_time)).strftime("%d/%m %H:%M"))

def update(val):
    t = slider.val
    U, Vv, C = compute_wind(t)
    q.set_UVC(U, Vv, C)
    slider.valtext.set_text((start_date + timedelta(hours=t)).strftime("%d/%m %H:%M"))
    idx = np.argmin(np.abs(time_list - t))
    boat_scatter.set_offsets([[longitude[idx], latitude[idx]]])
    fig.canvas.draw_idle()

slider.on_changed(update)
plt.show()

In [ ]:
fig = plt.figure(figsize=(6,6))
ax = plt.axes(projection=ccrs.Mercator())
ax.add_feature(cfeature.COASTLINE, linewidth=1)
# ax.add_feature(cfeature.NaturalEarthFeature('physical', 'land', '10m'), linewidth=1

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely import contains_xy
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def points_sur_terre_ou_mer(coords):
    coords[:, 0], coords[:, 1] = coords[:, 1] / 60, coords[:, 0] / (60 * 0.7)
    lat = coords[:, 0]
    lon = coords[:, 1]

    # Test vectorisé
    return ~contains_xy(land_geom, lon, lat)

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely.geometry import Point
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def valide_nm(x, y):
    lat, lon = y / 60, x / (60 * 0.7)
    p = Point(lon, lat)
    return not land_geom.contains(p)

def valide_deg(lat, lon):
    lon = lon - 360
    p = Point(lon, lat)
    return not land_geom.contains(p)

In [ ]:
valide_deg(46, 358)

In [ ]:
valide_nm(0 * 60 * 0.7, 46 * 60)

In [ ]:
VENT([46, 358], 6, 'deg')

In [ ]:
import cartopy.io.shapereader as shpreader
from shapely.geometry import Point
from shapely.ops import unary_union

# Charge les polygones de terre Natural Earth
land_shp = shpreader.natural_earth(
    resolution='10m',
    category='physical',
    name='land'
)

reader = shpreader.Reader(land_shp)
land_geom = unary_union(list(reader.geometries()))  # fusionne tous les polygones

def point_sur_terre_ou_mer(lat, lon):
    p = Point(lon, lat)   # attention : Point(x, y) = Point(lon, lat)
    return not land_geom.contains(p)

In [ ]:
point_sur_terre_ou_mer(46, 359)

In [ ]:
import pandas as pd
import numpy as np

def table_terre_mer(lat_start, lat_end, lon_start, lon_end, lat_step, lon_step):
    lats = np.arange(lat_start, lat_end + lat_step, lat_step)
    lons = np.arange(lon_start, lon_end + lon_step, lon_step)
    lat_grid, lon_grid = np.meshgrid(lats, lons, indexing='ij')
    flat_lats = lat_grid.ravel()
    flat_lons = lon_grid.ravel()
    # Utilise numpy pour la grille, mais reste une boucle sur le point_sur_terre_ou_mer
    values = np.array([point_sur_terre_ou_mer(lat, lon) for lat, lon in zip(flat_lats, flat_lons)])
    df = pd.DataFrame({
        "latitude": flat_lats,
        "longitude": flat_lons,
        "terre_mer": values
    })
    return df

# Exemple d'utilisation :
df = table_terre_mer(43.0, 50.0, -8.0, 0.0, 0.05, 0.05)
print(df)

In [ ]:
fig = plt.figure(figsize=(8, 6))
ax = plt.axes(projection=ccrs.PlateCarree())
scatter = ax.scatter(df["longitude"], df["latitude"], c=df["terre_mer"], cmap="bwr", marker="o", s=10, transform=ccrs.PlateCarree())
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
ax.set_title("Points Terre/Mer (0 = Terre, 1 = Mer)")
plt.colorbar(scatter, ticks=[0, 1], label="Terre (0) / Mer (1)")
ax.add_feature(cfeature.COASTLINE, linewidth=1)
plt.show()

In [ ]:
import pandas as pd

# On ouvre le fichier CSV data/polaires/vector.csv et on l'affiche
df = pd.read_csv("data/polaires/vector.csv")
df

In [ ]:
df.iloc[:, 0]

In [ ]:
df.iloc[0, 1:]

In [ ]:
df.iloc[:, 1:]